server:
  port: 9020
  servlet:
    context-path: /package-web

spring:
  datasource:
    url: jdbc:h2:mem:package;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

packaging:
  batch-size: 5
  timeout-minutes: 30
  storage-path: files
  master-key: "0123456789abcdef" # 16 bytes hex or base64 string
  remote-api-url: http://example.com/api/metadata
  token-url: http://example.com/oauth/token
  client-id: demo
  client-secret: demo

